### ISSUE TITLE
Not able to see salesforce cortex dashboards on marketplace

### ISSUE THREAD

**Issue by shrawanibawage** [looker-open-source/block-cortex-salesforce#1]
I am not able to see the Salesforce Dashboards plug-in in looker marketplace. can someone help me with the same

**Comment by benschuler** [comment]
Hi @99002688, the dashboards are not available directly through the marketplace, instead they can be installed from the Git URL by following the steps outlined here: https://cloud.google.com/looker/docs/marketplace#installing_a_tool_from_a_git_url

This method also allows you to use a different repository than our official one, for example if you want to make changes to the dashboards that we deliver as templates. The approach here could be for you to create a fork of our official repository, make the changes you would like to see, and then use the URL and commit SHA of your own repository in the dialog that is described above. This would allow you to customize the dashboards to your liking, while still having a connection to our official repository to be able to pull any updates from there into your own fork.

I hope this helps, let me know if there is anything else I can assist you with.

**Comment by benschuler** [comment]
Closing this issue as resolved. If you have any further questions, feel free to raise a new issue here with the specific details.
